/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
    // 1. 使能 GPIOA 时钟：RCC_APB2ENR bit2 = 1
    *(volatile uint32_t *)0x40021018 |= (1 << 2);

    // 2. 配置 PA5 为通用推挽输出，速度 2MHz
    // GPIOA_CRL 地址：0x40010800
    // PA5 对应 CRL 的 bit[23:20]
    *(volatile uint32_t *)0x40010800 &= ~(0xF << 20);
    *(volatile uint32_t *)0x40010800 |=  (0x2 << 20);

    while (1)
    {
        // 3. PA5 输出翻转
        *(volatile uint32_t *)0x4001080C ^= (1 << 5);

        // 4. 粗略延时
        for (volatile uint32_t i = 0; i < 500000; i++);
    }
}
